### ISSUE TITLE
mserver crash on start - Freebsd 10 amd64

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#3449]
Date: 2014-03-01 13:51:17 +0100
From: Jim Ohlstein &lt;<jim>&gt;
To:   clients devs &lt;<bugs-clients>&gt;
Version: 11.17.9 (Jan2014)
CC:   jim, @drstmane

Last updated: 2015-08-28 13:41:36 +0200

## Comment 19653
Date: 2014-03-01 13:51:17 +0100
From: Jim Ohlstein &lt;<jim>&gt;

User-Agent:       Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.117 Safari/537.36
 Build Identifier: 
 
 On testing the download of MonetDB-11.17.9-x86_64-FreeBSD-8.2-bin.tar.bz2 and trying to access a new database using "mclient" I get an error message as follows:
 
 monetdbd: internal error while starting mserver, please refer to the logs
 
 Reproducible: Always
 
 ### Steps to Reproduce:
 1. monetdbd start /usr/local/monetdb/var/monetdb5/dbfarm
 2. monetdb create voc
 3. monetdb release  voc
 4.mclient -u monetdb -d voc
 ### Actual Results:  
  mclient -u monetdb -d voc
 password: <monetdb>
 monetdbd: internal error while starting mserver, please refer to the logs
 
 ### Expected Results:  
 access the database without error.
 
 Entoire contents of log:
 
   cat /usr/local/monetdb/var/log/monetdb/merovingian.log
 2014-03-01 13:38:10 MSG merovingian[91347]: Merovingian 1.7 (Jan2014) starting
 2014-03-01 13:38:10 MSG merovingian[91347]: monitoring dbfarm /usr/local/monetdb/var/monetdb5/dbfarm
 2014-03-01 13:38:10 MSG merovingian[91347]: accepting connections on TCP socket 10.0.2.6:50000
 2014-03-01 13:38:10 MSG merovingian[91347]: accepting connections on UNIX domain socket /tmp/.s.monetdb.50000
 2014-03-01 13:38:10 MSG discovery[91347]: listening for UDP messages on 0.0.0.0:50000
 2014-03-01 13:38:10 MSG control[91347]: accepting connections on UNIX domain socket /tmp/.s.merovingian.50000
 2014-03-01 13:38:15 MSG control[91347]: (local): created database 'voc'
 2014-03-01 13:38:27 MSG control[91347]: (local): served status list
 2014-03-01 13:38:27 MSG control[91347]: (local): released database 'voc'
 2014-03-01 13:38:38 MSG merovingian[91347]: starting database 'voc', up min/avg/max: 0s/0s/0s, crash average: 0.00 0.00 0.00 (0-0=0)
 2014-03-01 13:38:38 MSG voc[91351]: arguments: /usr/local/monetdb/bin/mserver5 --dbpath=/usr/local/monetdb/var/monetdb5/dbfarm/voc --set merovingian_uri=mapi:monetdb://monetdb_jail:50000/voc --set mapi_open=false --set mapi_port=0 --set mapi_usock=/usr/local/monetdb/var/monetdb5/dbfarm/voc/.mapi.sock --set monet_vault_key=/usr/local/monetdb/var/monetdb5/dbfarm/voc/.vaultkey --set gdk_nr_threads=12 --set max_clients=64 --set sql_optimizer=default_pipe --set monet_daemon=yes
 2014-03-01 13:38:38 MSG merovingian[91347]: database 'voc' (91351) has exited with exit status 1
 2014-03-01 13:38:38 ERR merovingian[91347]: client error: database 'voc' appears to shut itself down after starting, check monetdbd's logfile for possible hints
 2014-03-01 13:38:38 MSG merovingian[91347]: starting database 'voc', up min/avg/max: 0s/0s/0s, crash average: 0.00 0.00 0.00 (0-0=0)
 2014-03-01 13:38:38 MSG voc[91352]: arguments: /usr/local/monetdb/bin/mserver5 --dbpath=/usr/local/monetdb/var/monetdb5/dbfarm/voc --set merovingian_uri=mapi:monetdb://monetdb_jail:50000/voc --set mapi_open=false --set mapi_port=0 --set mapi_usock=/usr/local/monetdb/var/monetdb5/dbfarm/voc/.mapi.sock --set monet_vault_key=/usr/local/monetdb/var/monetdb5/dbfarm/voc/.vaultkey --set gdk_nr_threads=12 --set max_clients=64 --set sql_optimizer=default_pipe --set monet_daemon=yes
 2014-03-01 13:38:38 MSG merovingian[91347]: database 'voc' (91352) has exited with exit status 1
 2014-03-01 13:38:39 ERR merovingian[91347]: client error: database 'voc' appears to shut itself down after starting, check monetdbd's logfile for possible hints

## Comment 19654
Date: 2014-03-01 14:56:53 +0100
From: Jim Ohlstein &lt;<jim>&gt;

Follow-up:
 
 Downloaded package does start up as expected on FreeBSD 8.4 amd64 and FreeBSD 9.2 amd64.
 
 Compiled version of 11.17.9 has same crash on FreeBSD 10.0 amd64. Same error shows if compiled with clang 3.3 or gcc46.
 
 Previous version (11.15.19) compiles and runs on FreeBSD 10.0 amd64.
 
 Will attache more detailed logs shortly.

## Comment 19655
Date: 2014-03-01 15:03:49 +0100
From: Jim Ohlstein &lt;<jim>&gt;

Created attachment 272
 log file

> Attached file: [merovingian.log](https://github.com/MonetDB/monetdb-issues-attachments/blob/master/issue_3449_merovingian.log_272) (text/plain, 225592 bytes)
> Description:   log file

## Comment 19656
Date: 2014-03-03 10:46:55 +0100
From: @drstmane

Jim,
 
 do I understand the following correctly:
 
 - after installing MonetDB-11.17.9-x86_64-FreeBSD-8.2-bin.tar.bz2 on a "virgin" (wrt. MonetDB, i.e., no old versions or databases left behind) mserver5 starts fine (on a new virgin database) on FreeBSD 8.4 & 9.2 but fails as reported on FreeBSD 10.0
 
 - compiling both 11.15.19 (Feb2013-SP6) and 11.17.9 (Jan2014) from source tarballs works fine on FreeBSD10.0, however, starting the server on a new virgin database only works fine with 11.15.19 (Feb2013-SP6), but fails as reported with 11.17.9 (Jan2014)
 
 ?
 
 Thanks!
 Stefan

## Comment 19658
Date: 2014-03-03 12:12:01 +0100
From: Jim Ohlstein &lt;<jim>&gt;

- after installing MonetDB-11.17.9-x86_64-FreeBSD-8.2-bin.tar.bz2 on a "virgin" (wrt. MonetDB, i.e., no old versions or databases left behind) mserver5 starts fine (on a new virgin database) on FreeBSD 8.4 & 9.2 but fails as reported on FreeBSD 10.0
 
 Yes. These tests were done on VirtualBox VM's for 8.4 and 9.2. For 10.0 they were done in a fresh jail on a 10.0-STABLE amd64 machine (r260997) and confirmed in a VirtualBOX VM running 10-0 RELEASE with a "GENERIC" kernel (FreeBSD freebsd-10.0-amd64 10.0-RELEASE FreeBSD 10.0-RELEASE 0 r260789: Thu Jan 16 22:34:59 UTC 2014     root@snap.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64) 
 
 
 - compiling both 11.15.19 (Feb2013-SP6) and 11.17.9 (Jan2014) from source tarballs works fine on FreeBSD10.0, however, starting the server on a new virgin database only works fine with 11.15.19 (Feb2013-SP6), but fails as reported with 11.17.9 (Jan2014)
 
 Correct. These tests were also done in fresh jails. I only tested these on FreeBSD 10-STABLE amd64.
 
 
 I did patch common/utils/mutils.c on BOTH versions to force compilation, without which an error is thrown during compilation:
 
 libtool: link: cc -g -O2 -D_REENTRANT -o .libs/mserver5 mserver5.o monet_version.o -pthread -Wl,--export-dynamic  ../../monetdb5/tools/.libs/libmonetdb5.so -L/usr/lib -L/usr/local/lib /root/MonetDB-11.15.19/gdk/.libs/libbat.so /root/MonetDB-11.15.19/clients/mapilib/.libs/libmapi.so -lreadline /usr/local/lib/libxml2.so -lz -llzma ../../gdk/.libs/libbat.so /root/MonetDB-11.15.19/common/stream/.libs/libstream.so /usr/local/lib/libiconv.so -lm -lbz2 -lkvm /usr/local/lib/libpcre.so -lssl -lcrypto -lumem -pthread -Wl,-rpath -Wl,/usr/local/lib
 /root/MonetDB-11.15.19/gdk/.libs/libbat.so: undefined reference to `backtrace_symbols'
 /root/MonetDB-11.15.19/gdk/.libs/libbat.so: undefined reference to `backtrace'
 cc: error: linker command failed with exit code 1 (use -v to see invocation)
 gmake[5]: *** [mserver5] Error 1
 
 The same error is seen on both versions and the same patch allowed compilation of both versions.
 
 The patch, as follows, had no effect on function of compiled versions of 11.15.19.
 
  cat patch-common-utils-mutils-c
 --- common/utils/mutils.c.orig	2014-02-02 18:51:49.389290318 +0100
 +++ common/utils/mutils.c	2014-02-02 18:55:21.300389407 +0100
 @@ -315,26 +315,7 @@
  
  ifdef HAVE_EXECINFO_H
  
 -/* Obtain a backtrace and print it to stdout. */
 -void
 -print_trace (void)
 -{
 -	void *array[10];
 -	size_t size;
 -	char **strings;
 -	size_t i;
 -
 -	size = backtrace (array, 10);
 -	strings = backtrace_symbols (array, size);
 -
 -	printf ("Obtained " SZFMT " stack frames.\n", size);
 -
 -	for (i = 0; i < size; i++)
 -		printf ("%s\n", strings[i]);
 -
 -	free (strings);
 -}
 -else
 +/* Backtrace not enabled. */
  void
  print_trace(void)
  {

## Comment 19770
Date: 2014-04-24 15:44:33 +0200
From: MonetDB Mercurial Repository &lt;<hg>&gt;

Changeset [de2ffe1f09ba](https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=de2ffe1f09ba)  made by Sjoerd Mullender <sjoerd@acm.org> in the MonetDB repo, refers to this bug.
 
 For complete details, see [http//devmonetdborg/hg/MonetDB?cmd=changeset;node=de2ffe1f09ba](https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=http//devmonetdborg/hg/MonetDB?cmd=changeset;node=de2ffe1f09ba) 
 
 Changeset description:
 
 	Check for existence of backtrace function.
 	This should fix the compilation problem noted in bug #3449.

## Comment 21126
Date: 2015-08-12 14:19:47 +0200
From: @sjoerdmullender

Closing since we now run mserver5 on FreeBSD 10.1 ourselved, and that seems to work.
 Note, the distributed binaries are still built on an ancient FreeBSD system.

## Comment 21180
Date: 2015-08-28 13:41:36 +0200
From: @sjoerdmullender

Jul2015 has been released.
