### ISSUE TITLE
monetdb start db -> dyld: Symbol not found: _SHA512

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#2277]
Date: 2009-12-10 01:39:57 +0100
From: Ben Companjen &lt;<bencompanjen>&gt;
To:   Niels Nes &lt;<niels>&gt;
Version: -- development

Last updated: 2009-12-10 01:42:40 +0100

## Comment 12831
Date: 2009-12-10 13:39:57 +0100
From: Ben Companjen &lt;<bencompanjen>&gt;

<offtopic>
 It took me forever (many tries, hours) to realize that the Nov2009 release will not compile on my MacBook Pro running OS X 10.5.8. I may file another report on this
 I managed to install Aug2009-SP2 with SQL and XQuery.
 </offtopic>
 
 Creating a database using 'monetdb create test' works fine. 'monetdb status' shows the database's status 'stopped'.
 When I want it to start, using 'monetdb start test', it crashes after starting. Terminal shows:
 $ monetdb start test
 starting database 'test'... FAILED:
 starting 'test' failed: database 'test' has crashed after starting, manual intervention needed, check merovingian's logfile for details
 
 The log then shows:
 2009-12-10 13:05:29 MSG merovingian[91012]: starting database 'test' due to control signal
 2009-12-10 13:05:29 MSG merovingian[91012]: starting database 'test', up min/avg/max: 0s/0s/0s, crash average: 0.00 0.00 0.00 (0-0=0)
 2009-12-10 13:05:29 MSG test[91301]: arguments: /Users/ben/MonetDB/bin/mserver5 --config=/Users/ben/MonetDB/etc/monetdb5.conf --dbname=test --dbinit=include sql; --set monet_daemon=yes --set mapi_open=false --set mapi_autosense=true --set mapi_port=50001 --set monet_vault_key=/Users/ben/MonetDB/var/MonetDB5/dbfarm/test/.vaultkey
 2009-12-10 13:05:29 ERR test[91301]: dyld: lazy symbol binding failed: Symbol not found: _SHA512
 2009-12-10 13:05:29 ERR test[91301]:   Referenced from: /Users/ben/MonetDB/lib/libmonetdb5.5.dylib
 2009-12-10 13:05:29 ERR test[91301]:   Expected in: flat namespace
 2009-12-10 13:05:29 ERR test[91301]: 
 2009-12-10 13:05:29 ERR test[91301]: dyld: Symbol not found: _SHA512
 2009-12-10 13:05:29 ERR test[91301]:   Referenced from: /Users/ben/MonetDB/lib/libmonetdb5.5.dylib
 2009-12-10 13:05:29 ERR test[91301]:   Expected in: flat namespace
 2009-12-10 13:05:29 ERR test[91301]: 
 2009-12-10 13:05:29 MSG merovingian[91012]: database 'test' (91301) was killed by signal 5
 2009-12-10 13:05:39 ERR merovingian[91012]: failed to fork mserver: database 'test' has crashed after starting, manual intervention needed, check merovingian's logfile for details
 
 Any ideas on this?

## Comment 12832
Date: 2009-12-10 13:42:40 +0100
From: Fabian Groffen &lt;<fabian>&gt;

yes, you failed to properly link the product.
 
 Dupe of 2911937

## Comment 12833
Date: 2010-05-04 09:32:09 +0200
From: Pseudo user for Sourceforge import &lt;<sfimport>&gt;

This bug was previously known as tracker item 2911975 at http://sourceforge.net/support/tracker.php?aid=2911975
 
 This bug was marked DUPLICATE in the database it was moved from.
     Changing resolution to "MOVED"
