### ISSUE TITLE
MonetDB compilation error on Ubuntu

### ISSUE THREAD

**Issue by PedroTadim** [MonetDB/MonetDB#7516]
Describe the bug
MonetDB compilation failed on my machine due to the following warnings converted to errors.

To Reproduce
Compile with -Wall flag enabled on GCC 10.5.0 and the following warnings will show:
```
In file included from monetdb_config.h:57,
                       from sql/server/sql_semantic.c:13:
sql/server/sql_semantic.c: In function ‘find_sequence_on_scope’:
sql/server/sql_semantic.c:124:10: error: the address of ‘objstr’ will always evaluate as ‘true’ [-Werror=address]
  124 |   assert(objstr); \
      |          ^~~~~~
sql/server/sql_semantic.c:188:2: note: in expansion of macro ‘search_object_on_path’
  188 |  search_object_on_path(res = find_sql_sequence(sql->session->tr, next, name), DO_NOTHING, ;, SQLSTATE(42000));
      |  ^~~~~~~~~~~~~~~~~~~~~
sql/server/sql_semantic.c: In function ‘find_idx_on_scope’:
sql/server/sql_semantic.c:124:10: error: the address of ‘objstr’ will always evaluate as ‘true’ [-Werror=address]
  124 |   assert(objstr); \
      |          ^~~~~~
sql/server/sql_semantic.c:198:2: note: in expansion of macro ‘search_object_on_path’
  198 |  search_object_on_path(res = mvc_bind_idx(sql, next, name), DO_NOTHING, ;, SQLSTATE(42S12));
      |  ^~~~~~~~~~~~~~~~~~~~~
sql/server/sql_semantic.c: In function ‘find_type_on_scope’:
sql/server/sql_semantic.c:124:10: error: the address of ‘objstr’ will always evaluate as ‘true’ [-Werror=address]
  124 |   assert(objstr); \
      |          ^~~~~~
sql/server/sql_semantic.c:208:2: note: in expansion of macro ‘search_object_on_path’
  208 |  search_object_on_path(res = schema_bind_type(sql, next, name), DO_NOTHING, ;, SQLSTATE(42S01));
      |  ^~~~~~~~~~~~~~~~~~~~~
sql/server/sql_semantic.c: In function ‘find_trigger_on_scope’:
sql/server/sql_semantic.c:124:10: error: the address of ‘objstr’ will always evaluate as ‘true’ [-Werror=address]
  124 |   assert(objstr); \
      |          ^~~~~~
sql/server/sql_semantic.c:218:2: note: in expansion of macro ‘search_object_on_path’
  218 |  search_object_on_path(res = mvc_bind_trigger(sql, next, name), DO_NOTHING, ;, SQLSTATE(3F000));
      |  ^~~~~~~~~~~~~~~~~~~~~
sql/server/sql_semantic.c: In function ‘find_variable_on_scope’:
sql/server/sql_semantic.c:124:10: error: the address of ‘objstr’ will always evaluate as ‘true’ [-Werror=address]
  124 |   assert(objstr); \
      |          ^~~~~~
sql/server/sql_semantic.c:259:2: note: in expansion of macro ‘search_object_on_path’
  259 |  search_object_on_path(var_find_on_global, DO_NOTHING, variable_extra, SQLSTATE(42000));
      |  ^~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
Expected behavior
The compilation should succeed.

**Software versions**
 - Latest compiled source on default branch.
 - OS and version: Ubuntu 22.04
 - Self-installed and compiled
