### ISSUE TITLE
gdk_system/MT_init fails to compile on FreeBSD 8.0

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#2555]
Date: 2010-06-13 02:06:13 +0200
From: hobury &lt;<info>&gt;
To:   GDK devs &lt;<bugs-common>&gt;
Version: 1.36.5 (Feb2010-SP2) [obsolete]
CC:   Stefan.Manegold

Last updated: 2010-08-20 14:03:49 +0200

## Comment 14090
Date: 2010-06-13 02:06:13 +0200
From: hobury &lt;<info>&gt;

User-Agent:       Mozilla/5.0 (X11; U; FreeBSD amd64; en-US; rv:1.9.1.7) Gecko/20100106 Firefox/3.5.7
 Build Identifier: 
 
 Tried to install MonetDB-Feb2010-SuperBall-SP2.
 
 The first error appears at:
 gdk_system.c:141: error: storage size of 'rl' isn't known
 
 
 Reproducible: Always
 
 ### Steps to Reproduce:
 These are the steps to reproduce:
 
 wget http://monetdb.cwi.nl/downloads/sources/Feb2010-SP2/MonetDB-Feb2010-SuperBall-SP2.tar.bz2
 bunzip2 MonetDB-Feb2010-SuperBall-SP2.tar.bz2
 tar -xf MonetDB-Feb2010-SuperBall-SP2.tar
 cd MonetDB-Feb2010-SuperBall-SP2
 ./monetdb-install.sh --prefix=/usr/local --enable-sql --enable-xquery
 
 This was attempted twice and after ensuring that sufficient disk space was available.
 
 ### Actual Results:  
 The errors appear as follows:
 gdk_system.c: In function 'MT_init':
 gdk_system.c:141: error: storage size of 'rl' isn't known
 gdk_system.c:147: warning: implicit declaration of function 'getrlimit'
 gdk_system.c:147: error: 'RLIMIT_DATA' undeclared (first use in this function)
 gdk_system.c:147: error: (Each undeclared identifier is reported only once
 gdk_system.c:147: error: for each function it appears in.)
 gdk_system.c:148: error: 'RLIM_INFINITY' undeclared (first use in this function)
 gmake[5]: *** [libbat_la-gdk_system.lo] Error 1
 gmake[5]: Leaving directory `/var/tmp/MonetDB-1276382852/MonetDB/MonetDB/src/gdk'
 gmake[4]: *** [all] Error 2
 gmake[4]: Leaving directory `/var/tmp/MonetDB-1276382852/MonetDB/MonetDB/src/gdk'
 gmake[3]: *** [all-recursive] Error 1
 gmake[3]: Leaving directory `/var/tmp/MonetDB-1276382852/MonetDB/MonetDB/src'
 gmake[2]: *** [all] Error 2
 gmake[2]: Leaving directory `/var/tmp/MonetDB-1276382852/MonetDB/MonetDB/src'
 gmake[1]: *** [all-recursive] Error 1
 gmake[1]: Leaving directory `/var/tmp/MonetDB-1276382852/MonetDB/MonetDB'
 gmake: *** [all] Error 2
 making MonetDB failed
 
 
 ### Expected Results:  
 Normal termination of installation script.
 
 
 uname -a
 FreeBSD pcbsd-5885 8.0-RELEASE-p2 FreeBSD 8.0-RELEASE-p2 10: Thu Jan  7 14:50:53 EST 2010     root@build8x64.pcbsd.org:/usr/obj/usr/pcbsd-build80/fbsd-source/8.0-src/sys/PCBSD  amd64

## Comment 14091
Date: 2010-06-13 10:35:18 +0200
From: Fabian Groffen &lt;<fabian>&gt;

Changeset [d3455d727e7f](https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=d3455d727e7f)  made by Fabian Groffen <fabian@cwi.nl> in the MonetDB repo, refers to this bug.
 
 For complete details, see [http//devmonetdborg/hg/MonetDB?cmd=changeset;node=d3455d727e7f](https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=http//devmonetdborg/hg/MonetDB?cmd=changeset;node=d3455d727e7f) 
 
 Changeset description:
 
 	include sys/time.h for FreeBSD for bug #2555, reorder includes such that the documentation matches

## Comment 14092
Date: 2010-06-13 10:41:48 +0200
From: Fabian Groffen &lt;<fabian>&gt;

can you please attach your build logfile?

## Comment 14093
Date: 2010-06-13 16:07:05 +0200
From: hobury &lt;<info>&gt;

Created attachment 7
 Log file
 
 Redid the procedure on a clean install:
 
 uname -a
 FreeBSD pcbsd-7236 8.0-RELEASE-p2 FreeBSD 8.0-RELEASE-p2 10: Thu Jan  7 14:50:53 EST 2010     root@build8x64.pcbsd.org:/usr/obj/usr/pcbsd-build80/fbsd-source/8.0-src/sys/PCBSD  amd64v

> Attached file: [log](https://github.com/MonetDB/monetdb-issues-attachments/blob/master/log) (text/plain, 33343 bytes)
> Description:   Log file

## Comment 14094
Date: 2010-06-13 16:13:22 +0200
From: Fabian Groffen &lt;<fabian>&gt;

Changeset [360847a980da](https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=360847a980da)  made by Fabian Groffen <fabian@cwi.nl> in the MonetDB repo, refers to this bug.
 
 For complete details, see [http//devmonetdborg/hg/MonetDB?cmd=changeset;node=360847a980da](https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=http//devmonetdborg/hg/MonetDB?cmd=changeset;node=360847a980da) 
 
 Changeset description:
 
 	FreeBSD has both sysconf and getrlimit, though to use the latter, it needs sys/resource.h include.  This should fix bug #2555

## Comment 14095
Date: 2010-06-13 16:19:54 +0200
From: Fabian Groffen &lt;<fabian>&gt;

Changeset [6b333af0bc16](https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=6b333af0bc16)  made by Fabian Groffen <fabian@cwi.nl> in the MonetDB repo, refers to this bug.
 
 For complete details, see [http//devmonetdborg/hg/MonetDB?cmd=changeset;node=6b333af0bc16](https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=http//devmonetdborg/hg/MonetDB?cmd=changeset;node=6b333af0bc16) 
 
 Changeset description:
 
 	include sys/time.h for FreeBSD for bug #2555, reorder includes such that the documentation matches
 	(transplanted from d3455d727e7f05e5582cf85529658cbeb1a4e5d9)

## Comment 14096
Date: 2010-06-13 16:19:55 +0200
From: Fabian Groffen &lt;<fabian>&gt;

Changeset [75848849b8db](https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=75848849b8db)  made by Fabian Groffen <fabian@cwi.nl> in the MonetDB repo, refers to this bug.
 
 For complete details, see [http//devmonetdborg/hg/MonetDB?cmd=changeset;node=75848849b8db](https://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=http//devmonetdborg/hg/MonetDB?cmd=changeset;node=75848849b8db) 
 
 Changeset description:
 
 	FreeBSD has both sysconf and getrlimit, though to use the latter, it needs sys/resource.h include.  This should fix bug #2555
 	(transplanted from 360847a980da29d039dd7ebe036f6fb38f7d68b8)

## Comment 14097
Date: 2010-06-13 16:25:27 +0200
From: Fabian Groffen &lt;<fabian>&gt;

A fix to your problem has been checked into the Jun2010 branch (the upcoming next release which is due to be released soon), since there will be no Feb2010 releases any more.
 
 Tomorrow around noon (CEST) you can download a Jun2010 supertarball preview from here that should include the fix:
 http://monetdb.cwi.nl/testing/projects/monetdb/Candidate/.DailyBuilds./0_latest/SourceSuperBall/

## Comment 14106
Date: 2010-06-14 20:08:10 +0200
From: hobury &lt;<info>&gt;

Created attachment 9
 Log file freebsd 7.3 amd64

> Attached file: [log](https://github.com/MonetDB/monetdb-issues-attachments/blob/master/log) (text/plain, 98780 bytes)
> Description:   Log file freebsd 7.3 amd64

## Comment 14107
Date: 2010-06-14 20:09:34 +0200
From: hobury &lt;<info>&gt;

Comment on attachment 9
 Log file freebsd 7.3 amd64
 
 The nightly build was also tested on a freebsd 7.3 machine (while no freebsd 8.0 machine is available for now):
 
 uname -a
 FreeBSD beijing.hobury.com 7.3-RELEASE FreeBSD 7.3-RELEASE 0: Sun Mar 21 05:25:24 UTC 2010     root@driscoll.cse.buffalo.edu:/usr/obj/usr/src/sys/GENERIC  amd64
 
 Error messages are possibly related.

## Comment 14108
Date: 2010-06-14 20:17:33 +0200
From: Fabian Groffen &lt;<fabian>&gt;

the freebsd7.3 problem appears to be a libtool problem that I can't really make any sense of.

## Comment 14109
Date: 2010-06-15 06:57:14 +0200
From: hobury &lt;<info>&gt;

(In reply to comment 10)
 > the freebsd7.3 problem appears to be a libtool problem that I can't really make
 > any sense of.
 
 So do you suggest that the installed libtool should be upgraded? Have there been other reports of FreeBSD 7.3 not being able to install MonetDB (and not logged in bugzilla)?

## Comment 14110
Date: 2010-06-15 07:22:16 +0200
From: Stefan Manegold &lt;<Stefan.Manegold>&gt;

What is the result of
 
 perl -MConfig -e '$x=$Config{installvendorarch}; $x =~ s|$Config{vendorprefix}/||; print $x;'
 
 on your FreeBSD 7.3 system?

## Comment 14111
Date: 2010-06-15 07:30:40 +0200
From: Stefan Manegold &lt;<Stefan.Manegold>&gt;

I'm not aware of any other reports regarding this problem on FreeBSD.
 
 However, the error 
 
 /bin/sh ../../../libtool   --mode=install /usr/bin/install -c   MapiLib.la '/usr/local/'
 libtool: install: error: cannot install `MapiLib.la' to a directory not ending in /usr/local/
 
 indeed seems to indicate a libtool problem --- whether libtool inherent or triggered by the MonetDB code base is not clear to me.
 
 The problem could also be perl and/or swig related (see my previous posting).
 
 
 Unless you need the perl DBI interface, you might also want to try to compile MonetDB without swig support by setting
 
 EXTRA_ECONF='--with-swig=no'
 
 in your shell environment before calling monetdb-install.sh

## Comment 14112
Date: 2010-06-15 22:28:19 +0200
From: hobury &lt;<info>&gt;

> What is the result of
 > 
 > perl -MConfig -e '$x=$Config{installvendorarch}; $x =~
 > s|$Config{vendorprefix}/||; print $x;'
 > 
 > on your FreeBSD 7.3 system?
 
 There is no result at all, and the command returns to the prompt.

## Comment 14123
Date: 2010-06-19 09:29:45 +0200
From: hobury &lt;<info>&gt;

Created attachment 10
 Log file  - 19-jun-2010 FreeBSD 8.0
 
 (In reply to comment 7)
 > Tomorrow around noon (CEST) you can download a Jun2010 supertarball preview
 > from here that should include the fix:
 > http://monetdb.cwi.nl/testing/projects/monetdb/Candidate/.DailyBuilds./0_latest/SourceSuperBall/
 
 Installation on FreeBSD 8.0 still failed, log file attached.

> Attached file: [log](https://github.com/MonetDB/monetdb-issues-attachments/blob/master/log) (application/octet-stream, 99349 bytes)
> Description:   Log file  - 19-jun-2010 FreeBSD 8.0

## Comment 14124
Date: 2010-06-19 10:36:47 +0200
From: Stefan Manegold &lt;<Stefan.Manegold>&gt;

Your FreeBSD 8.0 seems to experience the same problem as on your FreeBSD 7.3:
 
  /bin/sh ../../../libtool   --mode=install /usr/bin/install -c   MapiLib.la '/usr/local/'
 libtool: install: error: cannot install `MapiLib.la' to a directory not ending in /usr/local/
 
 The error as such looks self contradicting to me.
 
 It might be triggered (not necessarily caused) by the fact that your perl installation does not reveals its installation suffix the way we usually test for it (see my earlier request and your answer). I honestly have no idea why your perl does that or why your libtool then chokes.
 
 (
 BTW, which versio of Perl are you using?
 )
 
 Did/could you try my suggestion of skipping the compilation of the Perl/DBI interface by setting
 
 EXTRA_ECONF='--with-swig=no'
 
 in your shell environment before calling monetdb-install.sh ?

## Comment 14125
Date: 2010-06-19 10:50:36 +0200
From: Stefan Manegold &lt;<Stefan.Manegold>&gt;

Could you please also test what the following commands say on your FreeBSD systems:
 
 perl -V
 
 perl -V:installvendorarch -V:installvendorlib -V:vendorprefix
 
 Thanks!

## Comment 14126
Date: 2010-06-20 14:25:45 +0200
From: hobury &lt;<info>&gt;

Created attachment 11
 Perl version FreeBSD 8.0
 
 (In reply to comment 17)
 > Could you please also test what the following commands say on your FreeBSD
 > systems:
 > 
 > perl -V
 > 
 > perl -V:installvendorarch -V:installvendorlib -V:vendorprefix
 > 
 > Thanks!
 
 Please see attachment for the result of the commands above. I had tried the EXTRA_ECONF='--with-swig=no' setting, but it leads to a command not found. How exactly should it be run or entered?

> Attached file: [perl-version.txt](https://github.com/MonetDB/monetdb-issues-attachments/blob/master/perl-version.txt) (text/plain, 3106 bytes)
> Description:   Perl version FreeBSD 8.0

## Comment 14127
Date: 2010-06-20 14:44:14 +0200
From: Stefan Manegold &lt;<Stefan.Manegold>&gt;

The syntactic details for setting environment variables depend on your shell.
 
 In bash, you can use, e.g.,
 
  export EXTRA_ECONF='--with-swig=no'
  ./monetdb-install.sh ...

## Comment 14128
Date: 2010-06-20 23:13:42 +0200
From: hobury &lt;<info>&gt;

(In reply to comment 19)
 >  export EXTRA_ECONF='--with-swig=no'
 >  ./monetdb-install.sh ...
 
 The only difference in the log file is that line 10 now reads:
 ./configure --prefix='/usr/local' --disable-optimize --disable-debug --disable-assert --disable-strict --with-swig=no

**Comment by monetdb-team** [comment]
This comment was created automatically with main.py tool
## NOTE: Bugzilla Bug 2555 is renumbered to issue #2832
If you are looking for a Bugzilla Bug 2555, please follow issue #2832 instead.
