### ISSUE TITLE
Not all recently fixed bugs are documented by ChangeLog messages

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#2923]
Date: 2010-08-10 11:18:57 +0200
From: Stefan Manegold &lt;<Stefan.Manegold>&gt;
To:   Documentation maintainers &lt;<bugs-docs>&gt;
Version: unspecified

Last updated: 2010-08-31 10:21:14 +0200

## Comment 14631
Date: 2010-08-10 11:18:57 +0200
From: Stefan Manegold &lt;<Stefan.Manegold>&gt;

Not all bug IDs of bug reports that have been closed since July 10 2010 (or were closed before that but have been otherwise changed since then without re-opening them) do appear in any ChangeLog messages:
 
 $ for i in 2645 2641 2642 2591 2589 2613 2637 2611 2577 2548 2635 2617 2633 2636 2557 2606 2631 2614 2619 2626 2629 2628 2627 2624 2558 2623 2625 2622 2597 2592 2596 2610 2542 2573 2564 2547 2534 2598 ; do echo "$i `hg locate ChangeLog* | xargs grep -H $i`" ; done
 2645 sql/ChangeLog.Jun2010:- Fixed bug #2645: mat.pack+algebra.slice should be replaced by mat.slice
 2641 sql/ChangeLog.Jun2010:- Fixed bug #2641,  The SQL server now handles Unicode BOM sequences
 2642 
 2591 
 2589 
 2613 
 2637 
 2611 sql/ChangeLog.Jun2010:- Fix Bug #2611. Fixed check for multiple functions without parameters.
 2577 
 2548 
 2635 
 2617 
 2633 
 2636 
 2557 MonetDB5/ChangeLog.Jun2010:- Fixed bug #2557. There was a bug in the mergetable optimizer which was
 2606 sql/ChangeLog.Jun2010:- Fixed ORDER BY over UNION etc. (bug #2606) by
 2631 sql/ChangeLog.Jun2010:- Fixed bug in handling 'WITH' and row_number()  (Bug #2631).
 2614 MonetDB5/ChangeLog.Jun2010:  This fixes bugs 2626 & 2614.
 2619 clients/ChangeLog.Jun2010:  This fixes bug #2619.
 2626 MonetDB5/ChangeLog.Jun2010:  This fixes bugs 2626 & 2614.
 2629 
 2628 sql/src/backends/monet5/merovingian/ChangeLog.Jun2010:  observed in bug #2628.
 2627 java/ChangeLog.Jun2010:  and boxing/unboxing. Bug #2627
 2624 sql/ChangeLog.Jun2010:- Fixed bug #2624: function returning decimal returned result that was
 2558 clients/ChangeLog.Jun2010:  This fixes bug #2558.
 2623 sql/src/backends/monet5/merovingian/ChangeLog.Jun2010:  Linux, so make sure they time out. Fixes bug #2623838
 2625 
 2622 sql/ChangeLog.Jun2010:- fixed bug #2622 "LIMIT & OFFSET ignored on 64-bit big-endian when
 2597 
 2592 
 2596 MonetDB5/ChangeLog.Jun2010:  branch. This fixes bug #2596.
 2610 
 2542 
 2573 
 2564 
 2547 
 2534 
 2598

## Comment 14632
Date: 2010-08-10 11:48:25 +0200
From: Fabian Groffen &lt;<fabian>&gt;

$ for b in 2645 2641 2642 2591 2589 2613 2637 2611 2577 2548 2635 2617 2633 2636 2557 2606 2631 2614 2619 2626 2629 2628 2627 2624 2558 2623 2625 2622 2597 2592 2596 2610 2542 2573 2564 2547 2534 2598 ; do echo -n "$b" ; bugz get --base=http://bugs.monetdb.org/ --no-comments $b | grep Title | cut -d: -f2-; done
 2645 SQL: mat.pack+algebra.slice should be replaced by mat.slice for 'limit 1'
 2641 Unicode BOM upsets the scanner
 2642 tarantula.mx: uninitialized variables
 2591 missing/not-found file: "could not read createdb.sql"
 2589 CREATE TABLE & ALTER TABLE no longer produce "Operation successful"
 2613 SQL creates wrong MAL code a.o. with GDK_nr_threads=1
 2637 Mapi.mx: implicit declaration of function
 2611 creating second function with existing signature succeeds
 2577 not in (... union ...) differs from: except (... union ...)
 2548 Connect to default segfault
 2635 Unable to run select query on view if database is started readonly
 2617 Unexpected ORDER BY
 2633 crash in rel2bin with complex query and LIMIT
 2636 Subquery expected with group by, join
 2557 SQLException:assert:INSERT INTO: FOREIGN KEY constraint violated on 64-bits
 2606 ORDER BY over UNION / EXCEPT / INTERSECT is ignored
 2631 Combination of WITH and numbering function crashes Mserver
 2614 Update statement in function ignored
 2619 io.printf without newline hangs
 2626 Incorrect NULL function results with multi-thread execution
 2629 JDBC 1.15 and JunSP1 release compatible?
 2628 Cannot reconnect to same database twice
 2627 java/merovingian fails to compile on Debian 4.0
 2624 function returning decimal with fraction returns too large integer
 2558 unixODBC-2.3.0 removed SQLROWOFFSET and SQLROWSETSIZE
 2623 autogen.py hangs with new Python 2.7 on Windows
 2625 ODBC driver fails to compile on 64-bit MacOS X with Gentoo Prefix and unixODBC 2.3
 2622 LIMIT & OFFSET ignored on 64-bit big-endian when combined with GROUP BY
 2597 test sql/src/test/Tests/rank.sql produces varying (wrong?) output on various platforms
 2592 test sql/src/test/BugTracker-2009/Tests/dumping_tables.SF-2776908--optimizers.sql produces different output
 2596 some TPCH tests fail with assertion in opt_mergetable on Windows
 2610 selection of big arithmetic expression
 2542 Feb2010 database cannot be read by Jun2010 version
 2573 DB catalog corrupted after upgrade from Feb2010 to Jun2010
 2564 group-by column ordering fails if group-by columns are not in projection
 2547 Create schema causes segfault
 2534 Prepared statement with wrd arg type cannot be used
 2598 Wrong constraint in error message when delete prohibited due to foreign key

## Comment 14633
Date: 2010-08-10 12:38:41 +0200
From: Fabian Groffen &lt;<fabian>&gt;

these are the bugs without changelog entries (according to Stefan's grep)
 
 $ for b in 2642 2591 2589 2613 2637 2577 2548 2635 2617 2633 2636 2629 2625 2597 2592 2610 2542 2573 2564 2547 2534 2598 ; do echo -n "$b" ; bugz get --base=http://bugs.monetdb.org/ --no-comments $b | grep Title | cut -d: -f2-; done
 2642 tarantula.mx: uninitialized variables
 2591 missing/not-found file: "could not read createdb.sql"
 2589 CREATE TABLE & ALTER TABLE no longer produce "Operation successful"
 2613 SQL creates wrong MAL code a.o. with GDK_nr_threads=1
 2637 Mapi.mx: implicit declaration of function
 2577 not in (... union ...) differs from: except (... union ...)
 2548 Connect to default segfault
 2635 Unable to run select query on view if database is started readonly
 2617 Unexpected ORDER BY
 2633 crash in rel2bin with complex query and LIMIT
 2636 Subquery expected with group by, join
 2629 JDBC 1.15 and JunSP1 release compatible?
 2625 ODBC driver fails to compile on 64-bit MacOS X with Gentoo Prefix and unixODBC 2.3
 2597 test sql/src/test/Tests/rank.sql produces varying (wrong?) output on various platforms
 2592 test sql/src/test/BugTracker-2009/Tests/dumping_tables.SF-2776908--optimizers.sql produces different output
 2610 selection of big arithmetic expression
 2542 Feb2010 database cannot be read by Jun2010 version
 2573 DB catalog corrupted after upgrade from Feb2010 to Jun2010
 2564 group-by column ordering fails if group-by columns are not in projection
 2547 Create schema causes segfault
 2534 Prepared statement with wrd arg type cannot be used
 2598 Wrong constraint in error message when delete prohibited due to foreign key

## Comment 14636
Date: 2010-08-10 23:52:36 +0200
From: Stefan Manegold &lt;<Stefan.Manegold>&gt;

ChangeLog messages of the following bug reports
 
 2591 missing/not-found file: "could not read createdb.sql"
 2597 test sql/src/test/Tests/rank.sql produces varying (wrong?) output on various platforms
 2564 group-by column ordering fails if group-by columns are not in projection
 
 had already been to the *.spec file before releasing Jun2010-SP1:
 
 2591: sql/MonetDB-SQL.spec:  a newly created database.  Bug #2591
 2597: MonetDB5/MonetDB-server.spec:- Fixed bug #2597: This bug manifested itself in rank queries in SQL
 2564: sql/MonetDB-SQL.spec:- fixed bug #2564: in case group by column is not found as alias in

## Comment 14854
Date: 2010-08-30 09:27:05 +0200
From: Sjoerd Mullender &lt;<sjoerd>&gt;

I've gone through the bugs and added changelog messages where I thought appropriate.
 Closing now since the release is out the door.
