### ISSUE TITLE
mel fails to compile with icc 8.1 on Fedora Core 3 / 64 bit

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#530]
Date: 2005-05-05 10:49:54 +0200
From: Stefan Manegold &lt;<Stefan.Manegold>&gt;
To:   Sjoerd Mullender &lt;<sjoerd>&gt;
Version: -- development

Last updated: 2005-05-05 11:26:42 +0200

## Comment 2905
Date: 2005-05-05 10:49:54 +0200
From: Stefan Manegold &lt;<Stefan.Manegold>&gt;

From
 http://monetdb.cwi.nl/testing/projects/monetdb/Current/MonetDB/.ntv_64-d/Fedora3/make.out:
 ========
 [...]
 icpc -no-gcc -DHAVE_CONFIG_H -I.
 -I/tmp/monet.ntv_64-d.22780/MonetDB/src/mel -I../..
 -I/tmp/monet.ntv_64-d.22780/MonetDB/src/mel -we140
 -wd1418 -c99 -Wall -w2  -c -o mel.yy.o mel.yy.cc
 [...]
 /usr/include/c++/3.4.3/bits/postypes.h(72): error:
 identifier "int64_t" is undefined
     typedef int64_t       streamoff;
             ^
 [...]
 compilation aborted for mel.yy.cc (code 2)
 make[4]: *** [mel.yy.o] Error 2
 make[4]: Leaving directory
 `/tmp/monet.ntv_64-d.22780/MonetDB/Fedora3/src/mel'
 make[3]: *** [all] Error 2
 make[3]: Leaving directory
 `/tmp/monet.ntv_64-d.22780/MonetDB/Fedora3/src/mel'
 make[2]: *** [all-recursive] Error 1
 make[2]: Leaving directory
 `/tmp/monet.ntv_64-d.22780/MonetDB/Fedora3/src'
 make[1]: *** [all-recursive] Error 1
 make[1]: Leaving directory
 `/tmp/monet.ntv_64-d.22780/MonetDB/Fedora3'
 make: *** [all] Error 2
 ========
 

## Comment 2906
Date: 2005-05-05 11:26:42 +0200
From: Niels Nes &lt;<niels>&gt;

Logged In: YES 
 user_id=43556
 
 fixed /usr/include/features.h. This file doesn't handle the
 x86_64 case for the  
 intel compiler jet. Lets hope the next release of glibc
 includes the fix.

## Comment 2907
Date: 2005-11-09 14:14:42 +0100
From: Sjoerd Mullender &lt;<sjoerd>&gt;

Logged In: YES 
 user_id=43607
 
 BugDay_2005-11-09, sjoerd: NO TEST / COMPILATION

## Comment 2908
Date: 2010-05-04 09:32:09 +0200
From: Pseudo user for Sourceforge import &lt;<sfimport>&gt;

This bug was previously known as tracker item 1195753 at http://sourceforge.net/support/tracker.php?aid=1195753
