### ISSUE TITLE
GCC 3.4 should not be invoked `-ansi -std=c99'

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#413]
Date: 2004-12-09 03:51:19 +0100
From: Jens Teubner &lt;<teubner>&gt;
To:   Stefan Manegold &lt;<Stefan.Manegold>&gt;
Version: -- development

Last updated: 2004-12-10 10:04:14 +0100

## Comment 2241
Date: 2004-12-09 15:51:19 +0100
From: Jens Teubner &lt;<teubner>&gt;

Current Pathfinder CVS does not compile on GCC 3.4.3:
 
 array.c: In function `PFarray_vprintf':
 array.c:223: error: implicit declaration of function `va_copy'
 
 va_copy() was introduced with C99. GCC 3.4 is invoked with `-ansi 
 -std=c99' and does thus not support C99. This problem is similar to 
 other C99 issues we had seen in the past (e.g., initialization of 
 variables in for(;;) loops).
 
 conf/monet.m4 sets `-ansi -std=c99' for GCC 3.x, except for GCC 3.
 3, where (correctly) only `-std=c99' is set. I've patched monet.m4 
 on my system as below, which solves the problem for me.
 
 However, I have no clue, why `-ansi' is set at all for GCC 3.x. 
 Seems like it doesn't make trouble on GCC 3.[0-2], but demanding 
 two standards at once (ISO C90 and C99) doesn't really make sense, 
 does it? So should we even omit `-ansi' for all the GCC 3.x versions, 
 or does that break anything on other systems?
 
 
 *** /opt/MonetDB-4.4.2/share/MonetDB/conf/monet.m4      Thu Dec  
 9 15:34:28 2004
 --- /home/teubner/work/monet/MonetDB/conf/monet.m4      Mon 
 Nov 15 15:38:45 2004
 ***************
 *** 237,247 ****
         *-solaris*)
                 AC_DEFINE(__EXTENSIONS__, 1, [Compiler flags])
                 ;;
         *-irix*|*-cygwin*|*-darwin*|2.*-*)
                 ;;
 !       3.[[3-4]]*-*)
                 AC_DEFINE(_POSIX_C_SOURCE, 199506L, [Compiler 
 flag])
                 AC_DEFINE(_POSIX_SOURCE, 1, [Compiler flag])
                 AC_DEFINE(_XOPEN_SOURCE, 600, [Compiler flag])
                 CFLAGS="$CFLAGS -std=c99"
                 CXXFLAGS="$CXXFLAGS -ansi"
 --- 237,247 ----
         *-solaris*)
                 AC_DEFINE(__EXTENSIONS__, 1, [Compiler flags])
                 ;;
         *-irix*|*-cygwin*|*-darwin*|2.*-*)
                 ;;
 !       3.3*-*)
                 AC_DEFINE(_POSIX_C_SOURCE, 199506L, [Compiler 
 flag])
                 AC_DEFINE(_POSIX_SOURCE, 1, [Compiler flag])
                 AC_DEFINE(_XOPEN_SOURCE, 600, [Compiler flag])
                 CFLAGS="$CFLAGS -std=c99"
                 CXXFLAGS="$CXXFLAGS -ansi"
 

## Comment 2242
Date: 2004-12-10 22:04:14 +0100
From: Stefan Manegold &lt;<Stefan.Manegold>&gt;

Logged In: YES 
 user_id=572415
 
 fixed in CVS.
 

## Comment 2243
Date: 2005-11-09 12:51:11 +0100
From: Sjoerd Mullender &lt;<sjoerd>&gt;

Logged In: YES 
 user_id=43607
 
 BugDay_2005-11-09, sjoerd: NO TEST / COMPILATION

## Comment 2244
Date: 2010-05-04 09:32:09 +0200
From: Pseudo user for Sourceforge import &lt;<sfimport>&gt;

This bug was previously known as tracker item 1082161 at http://sourceforge.net/support/tracker.php?aid=1082161
